import { readFileSync } from 'node:fs';
import { defineConfig } from 'wxt';
import tailwindcss from '@tailwindcss/vite';

const pkg = JSON.parse(
  readFileSync(new URL('./package.json', import.meta.url), 'utf8'),
) as { version: string };

// WXT configuration.
//
// Standing v2 constraints (see root CLAUDE.md):
//  - MV3 for BOTH Chromium and Gecko (Firefox).
//  - The background service worker / event page and per-browser manifest are
//    GENERATED by WXT — never hand-write a background.
//  - Use the unified `browser.*` namespace (WXT polyfill). Never `chrome.*`.
//
// https://wxt.dev/api/config.html
export default defineConfig({
  srcDir: '.',
  modules: ['@wxt-dev/module-vue'],
  manifestVersion: 3,

  // Clean artifact names: faker-js-ui-<version>-<browser>.zip (+ -sources.zip
  // for Firefox/AMO).
  zip: {
    name: 'faker-js-ui',
  },

  // Add the Tailwind v4 Vite plugin into WXT's Vite pipeline.
  vite: () => ({
    plugins: [tailwindcss()],
    // Single source of truth for the version shown outside an extension
    // context (e.g. when popup.html is loaded directly in a test/preview).
    define: {
      __APP_VERSION__: JSON.stringify(pkg.version),
    },
  }),

  // Per-browser manifest so Firefox-only AMO metadata never leaks into the
  // Chrome artifact.
  manifest: ({ browser }) => ({
    name: 'Faker.js UI',
    description: 'Simple and intuitive UI for Faker.js',
    // `default_popup` is injected automatically from entrypoints/popup.
    action: {
      default_title: 'Faker.js UI',
    },
    // Minimal permissions: the popup messages the active tab's auto-fill content
    // script. `storage` isn't needed (we use localStorage); `scripting` would
    // only be needed for the lazy-injection optimisation tracked separately.
    permissions: ['activeTab'],
    host_permissions: ['*://*/*'],
    // Firefox (AMO) requirements. strict_min_version is re-validated in Phase 6
    // when the auto-fill content script lands; packaging is finalised in Phase 7.
    ...(browser === 'firefox'
      ? {
          browser_specific_settings: {
            gecko: {
              id: 'faker-js-ui@fakerjsui.org',
              strict_min_version: '109.0',
              // AMO requires new extensions to declare data collection. None collected.
              data_collection_permissions: {
                required: ['none'],
              },
            },
          },
        }
      : {}),
  }),
});
